### ISSUE TITLE
Segfaults when connecting a browser to Node.js

### ISSUE THREAD

**Issue by ReidWilliams** [libp2p/js-libp2p-webrtc-star#100]
We're seeing a lot of segfaults when we use webrtc-star as a transport and connect an IPFS instance running in a browser to one running on Node.js.

Right now we're trying to get reproducible test cases that cause the segfaults. What we've noticed so far is that segfaults only happen when a browser is connecting to Node.js running inside a docker container. Node.js to Node.js inside a container works fine, and browser to Node.js on MacOs works fine too.

Stack traces leading up to the segfault are confusing. Sometimes we see functions from the `wrtc` module but sometimes all functions are node or libuv.

`wrtc` seems like a likely candidate for causing this (there are plently of issues in their repo about segfaults) but I'm confused about stack traces leading to segfaults that do not contain any `wrtc` function calls. Is it possible that `wrtc` misbehaves by corrupting some state but the actual stack trace leading up to the segfault only contains node/libuv calls?

Are there other compiled Node addons that might be suspects in causing this (e.g. I know there are compiled crypto addons)? 

Are there any known incompatibilities between `wrtc` and the native browser implementation of WebRTC that might cause this?

@gavinmcdermott

**Comment by VictorBjelkholm** [comment]
Yeah, there seems to be something weird happening with `wrtc` on linux, there is a existing issue about Ubuntu specifically here: https://github.com/libp2p/js-libp2p-webrtc-star/issues/57

**Comment by ReidWilliams** [comment]
Just tried a couple more things to be more sure: I'm seeing segfaults when connecting browser to Node.js when Node.js is running in a docker container and when running outside of a container on Debian.

**Comment by ReidWilliams** [comment]
Now also seeing segfaults when running two Node.js instances talking to each other.

**Comment by VictorBjelkholm** [comment]
Hm, I've seen crashes when doing `browser <> node` connections, but never `node <> node`, so might be a different issue.

**Comment by diasdavid** [comment]
Still seeing this issue @ReidWilliams ? `wrtc` is in fact very unstable, any feedback that can be provided to authors is highly appreciated because it simply doesn't get enough testing.

Do you have easy repro cases?

**Comment by RodZokos** [comment]
I am getting segmentation fault too. I am running Ubuntu 14.04.5 and node v7.7.3

**Comment by rodkeys** [comment]
I am getting segmentation fault too. I am running Ubuntu 14.04.5 and node v7.7.3

**Comment by diasdavid** [comment]
Hi @ReidWilliams

Long time no see! I hope everything is great with you.

We've started noticing more of this issue and ended up enabling the option for users to pick their own WebRTC shim for Node.js, today we have two `wrtc` and `electron-webrtc` and the second looks more stable than the first.
