### ISSUE TITLE
Multiaddrs need to be changed

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-webrtc-star#110]
As per @lgierth recommendation and review, a libp2p-webrtc-star multiaddr should be:

`/dns4/star-signal.cloud.ipfs.team/wss/libp2p-webrtc-star/ipfs/<your-peer-id>`

**Comment by lgierth** [comment]
Does the webrtc stuff happen over websockets? I.e., does `/dns4/star-signal.cloud.ipfs.team/wss/libp2p-webrtc-star` yield full dialable addresses that match `/ipfs/<your-peer-id>`?

**Comment by diasdavid** [comment]
I'm 85% positive I got your question, so here is my best shot at the answer:

We need the `/ipfs/<peer-id>` because we need to know which peer we are trying to dial through the signalling endpoint

**Comment by lgierth** [comment]
Yeah :) And does the signalling happen over /wss?

**Comment by lgierth** [comment]
I'm just not sure because js-libp2p-webrtc-star is still this magic blackbox to me :)

**Comment by diasdavid** [comment]
> Yeah :) And does the signaling happen over /wss?

It does. However, it could happen through any other libp2p stream to a node.

I want to have the signalling server be a libp2p node that mounts the webrtc-star-signalling protocol. This way go-ipfs will be able to handle it too :)

**Comment by lgierth** [comment]
We discussed yesterday that the scheme should probably `/dns4/example.net/tcp/443/wss/p2p-webrtc-star/ipfs/QmDestination`. I had one more thought which is that p2p-webrtc-star isn't a libp2p swarm protocol -- should we mark that in the scheme name? We could name it sig-webrtc-star instead (for "signaling").

**Comment by diasdavid** [comment]
They have changed now :)
