### ISSUE TITLE
How to get the ipfs peer-id?

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-libp2p-webrtc-star#115]
I have my signaling server up and running but have no idea how to get the peer-id for the /ipfs/ url.

Is that the peer-id from .ipfs/config? Could that be mentioned more clearly in the README?

**Comment by mkg20001** [comment]
I've realized that the signaling server has no peer-id.

**Comment by diasdavid** [comment]
👍 I was just about to post a reply but you were faster to close it :)

**Comment by pynchmeister** [comment]
> I've realized that the signaling server has no peer-id.

how did you achieve creating the peer-id on the signaling server setup?
