### ISSUE TITLE
Deploy to wrtc-star.discovery.libp2p.io

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-webrtc-star#126]
> From the proposal made on IRC

**Comment by VictorBjelkholm** [comment]
https://wrtc-star.discovery.libp2p.io/ is live now :)

**Comment by jacobheun** [comment]
The deploys for signaling servers need to be updated (they're currently not establishing connections), I'm working on getting that done soon. In the mean time I'd recommend trying to run the signaling server locally, https://github.com/libp2p/js-libp2p-webrtc-star#rendezvous-server-aka-signalling-server. I've verified that it's working locally.

I've created an issue to track the deployment update, https://github.com/libp2p/js-libp2p-webrtc-star/issues/180.

**Comment by pynchmeister** [comment]
Awesome, thank you! I'll give the local signaling server a shot...
