### ISSUE TITLE
Error: invalid multiaddr: /dns4/...

### ISSUE THREAD

**Issue by fazo96** [libp2p/js-libp2p-webrtc-star#134]
Hello, I get this when I start up js-ipfs in the browser

```
Error: invalid multiaddr: /dns4/star-signal.cloud.ipfs.team/wss/p2p-webrtc-star/ipfs/QmQGbDesZ8ihd1tA9XHkY7gromHywcvSR7jKb4zxjPqSc2
```

Then it looks like it's not able to connect to any other node at all.

I narrowed it down to updating this module from 0.13.2 to 0.13.3, in fact by putting this in the `package.json`

```
  "resolutions": {
    "libp2p-webrtc-star": "0.13.2"
  },
```

Everything works again

**Comment by mkg20001** [comment]
This does not work anymore as per resolution in #129 
`/dns4/star-signal.cloud.ipfs.team/tcp/443/wss/p2p-webrtc-star/ipfs/QmQGbDesZ8ihd1tA9XHkY7gromHywcvSR7jKb4zxjPqSc2` should be used instead (see #133)
