### ISSUE TITLE
Peer can be discovered but isn't discovering other peers

### ISSUE THREAD

**Issue by owenauch** [libp2p/js-libp2p-webrtc-star#150]
Hi, I was working with `js-libp2p-webrtc-star` for the first time, and I was struggling with getting connected to a simple signaling server and discovering peers. I had one peer running with a browser implementation and one running in Node, and both were trying to connect to the same signaling server. When I start both up, I can see the `peer:discovery` event being triggered for the browser-based implementation when it finds the Node-based peer, but the Node peer's `peer:discovery` isn't triggered. Here's the code for the node peer:
```
"use strict";

const wrtc = require("wrtc");
const libp2p = require("libp2p");
const PeerInfo = require("peer-info");
const WebRTCStar = require("libp2p-webrtc-star");
const KadDHT = require("libp2p-kad-dht");
const defaultsDeep = require("@nodeutils/defaults-deep");

class Node extends libp2p {
  constructor(_peerInfo, _peerBook, _options) {
    const wstar = new WebRTCStar({ wrtc: wrtc });
    const defaults = {
      peerInfo: _peerInfo,
      
      modules: {
        transport: [wstar],
        peerDiscovery: [wstar.discovery],
        dht: KadDHT
      }
    };

    super(defaultsDeep(_options, defaults));
  }
}

function createNode(callback) {
  PeerInfo.create((err, peerInfo) => {
    if (err) {
      return callback(err);
    }

    const peerIdStr = peerInfo.id.toB58String();
    const ma = `/dns4/localhost/tcp/9090/ws/p2p-webrtc-star/ipfs/${peerIdStr}`;

    peerInfo.multiaddrs.add(ma);
    const node = new Node(peerInfo);
    node.idStr = peerIdStr;
    callback(null, node);
  });
}

createNode((err, node) => {
  if (err) {
    return console.log("Could not create the Node, t", err);
  }

  node.on("peer:discovery", peerInfo => {
    const idStr = peerInfo.id.toB58String();
    console.log("Discovered a peer:", idStr);
  });

  node.start(err => {
    if (err) {
      return console.log("WebRTC not supported");
    }
    const idStr = node.peerInfo.id.toB58String();
    console.log("Node " + idStr + " has just started");
  });
});
```

Anyone know why it would work only one way like that?

**Comment by jacobheun** [comment]
Hi @owenauch, it looks like you're using the most recently released libp2p here, based on the configuration. Since I can't see your browser setup I'm not sure if you're using an older version or if you config is different resulting in webrtc-star discovery working.

The reason the node version isn't working has to do with the default enabling of peerDiscovery modules, which is currently disabled by default. This is being corrected by https://github.com/libp2p/js-libp2p/pull/209. 

Until that is updated, which should be soon, you'll need to enable peerDiscovery explicitly by updating your defaults to something like:

```js
const defaults = {
  peerInfo: _peerInfo,      
  modules: {
    transport: [wstar],
    peerDiscovery: [wstar.discovery],
    dht: KadDHT
  },
  config: {
    peerDiscovery: {
      [wstar.discovery.tag]: {
        enabled: true
      }
    }
  }      
};
```
This should resolve the issue you are hitting.

**Comment by owenauch** [comment]
That fixed it, thank you!

**Comment by gitGksgk** [comment]
@jacobheun  must i setup a Rendezvous server or Signalling server so as to enable browser node peer discovery ?

**Comment by jacobheun** [comment]
@gitGksgk you will need to connect to a rendezvous server in order to discover other nodes. We do host a rendezvous server you can use for testing, https://github.com/libp2p/js-libp2p-webrtc-star#hosted-rendezvous-server, but it's recommended to host your own for production applications.
