### ISSUE TITLE
PeerInfo must be passed multiaddr instances to respect https and wss

### ISSUE THREAD

**Issue by asselstine** [libp2p/js-libp2p-webrtc-star#155]
I set my own WebRTC star server behind an NGINX reverse proxy with SSL and tried setting up a node as per the example:

```javascript
const ma = `/dns4/${hostname}/tcp/443/wss/p2p-webrtc-star/ipfs/${peerIdStr}`
peerInfo.multiaddrs.add(ma)
const node = newNode({
  peerInfo
})
```

But that didn't work- I had to actually wrap the string in a `multiaddr` object to get it to respect SSL:

```javascript
const multiaddr = require('multiaddr')
// ...
const ma = multiaddr(`/dns4/${hostname}/tcp/443/wss/p2p-webrtc-star/ipfs/${peerIdStr}`)
peerInfo.multiaddrs.add(ma)
const node = newNode({
  peerInfo
})
```

Hope that helps somebody.

**Comment by vasco-santos** [comment]
Thanks @asselstine !

Are you interested in adding an example folder for this use case? Or adding a section on `README.md`?

**Comment by asselstine** [comment]
Thanks for the invitation.  I feel it may merit more of a PR actually.  It strikes me as inconsistent that the library expects multiaddr strings, but it doesn't fully use them unless you pass it wrapped as a multiaddr object.

If I find some time I'll submit a PR.  I'd be happy to contribute as I quite like libp2p so far.
