### ISSUE TITLE
some time "this.listenersRefs[Object.keys(this.listenersRefs)[0]]" is undefined and throw and error

### ISSUE THREAD

**Issue by mccoysc** [libp2p/js-libp2p-webrtc-star#158]
const sioClient = this
.listenersRefs[Object.keys(this.listenersRefs)[0]].io

some time "this.listenersRefs[Object.keys(this.listenersRefs)[0]]" is undefined and throw and error.

this line is in libp2p-webrtc-star/src/index.js @line 63

**Comment by mccoysc** [comment]
`
![1](https://user-images.githubusercontent.com/18025276/46475182-6b039500-c817-11e8-8bc6-2e577ff38707.png)
`

**Comment by mccoysc** [comment]
![1](https://user-images.githubusercontent.com/18025276/46475202-7bb40b00-c817-11e8-958c-066f871c066d.png)

**Comment by mkg20001** [comment]
Could you check if the change from PR #160 fixes your issue?

**Comment by vasco-santos** [comment]
Closing this as it should be fixed. Feel free to open it if you find this problem again
