### ISSUE TITLE
Uncaught DOMException: Failed to construct 'RTCPeerConnection': Cannot create so many

### ISSUE THREAD

**Issue by mccoysc** [libp2p/js-libp2p-webrtc-star#159]
config: {
Addresses: {
Swarm: [
'/dns4/wrtc-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star/'
]
}
},

got this error as title.

self._pc = new (self._wrtc.RTCPeerConnection)(self.config, self.constraints)

**Comment by jacobheun** [comment]
@mccoysc which version of `libp2p-webrtc-star` are you running? The recent release, v0.15.5, added a fix to catch this error. https://github.com/libp2p/js-libp2p-webrtc-star/pull/157

**Comment by mccoysc** [comment]
I just use the ipfs version 0.32.3……does it would not update with ipfs?

**Comment by jacobheun** [comment]
If you have a package-lock file it may be locking the version at 0.15.3.  I fresh install or updating your packages should pull in the latest.

**Comment by diasdavid** [comment]
@mccoysc seems that you got your answer. Let us know if it worked. Closing, reopen later if necessary.
