### ISSUE TITLE
Reenable prometheus with epimetheus

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p-webrtc-star#174]
When updating `hapi` from v16 to v18, the current implementation of `epimetheus` was not yet updated to use the new promises api, instead of the previous callback logic.

Needs: https://github.com/roylines/node-epimetheus/issues/43

**Comment by achingbrain** [comment]
You should be able to use [achingbrain/menoetius](https://github.com/achingbrain/menoetius) in it's place..
