### ISSUE TITLE
webrtc-star/simple peer errors, setRemoteDescription

### ISSUE THREAD

**Issue by tabcat** [libp2p/js-libp2p-webrtc-star#251]
Instructed to move https://github.com/ipfs/js-ipfs/issues/3231 here

**Comment by vasco-santos** [comment]
Thanks for reporting this @tabcat 
Would you like to PR this change?

**Comment by tabcat** [comment]
I can try, I will take a closer look after our HackFS presentation today :)
I've never seen a `cannot assign read only property 'message' of object ''` error before though, so any info on that would be helpful.

**Comment by vasco-santos** [comment]
It seems that who creates the error somehow makes it read only (with a proxy or similar). If that is the case, I think we can just not assign the error message and log it, as there is nothing we can do
