### ISSUE TITLE
Node.js 15 CI tests

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p-webrtc-star#266]
Per #264 , Node.js 15 CI job should be integrated. `interface-transport` tests are currently failing

**Comment by SonataOto** [comment]
Actually, this repository fail at deploy about Node versions >=15 <=16.

**Comment by achingbrain** [comment]
CI for this repo runs on node 16 now - https://github.com/libp2p/js-libp2p-webrtc-star/actions
