### ISSUE TITLE
Upgrader is not defined. 

### ISSUE THREAD

**Issue by ubernaut** [libp2p/js-libp2p-webrtc-star#267]
I'm trying to perform a "hello world" type example of libp2p using webrtc-star where I can make two peers communicate. 

Having trouble with the browser usage guide from the readme. I understand that I need an Upgrader but I'm not sure how to instantiate one. 

If that is out of scope for this project,
Can you point me to a complete self contained example of standing up a libp2p node using webrtc-star?  The Getting Started guide from libp2p uses bootstrap and looks pretty different from the webrtc-star example. 

as an aside, do I need to generate my own key pair to use the example or can I use the multiaddr string from the example?

**Comment by vasco-santos** [comment]
Hello @ubernaut 
While you can create an [upgrader](https://github.com/libp2p/js-libp2p-interfaces/tree/master/src/transport#upgrader) yourself, it is not trivial and if you are relying on libp2p you should just rely on its own upgrader. I recommend you to leverage the [libp2p/js-libp2p/examples/libp2p-in-the-browser](https://github.com/libp2p/js-libp2p/tree/master/examples/libp2p-in-the-browser) for getting to know how to use this. 

> Can you point me to a complete self contained example of standing up a libp2p node using webrtc-star? The Getting Started guide from libp2p uses bootstrap and looks pretty different from the webrtc-star example.

> as an aside, do I need to generate my own key pair to use the example or can I use the multiaddr string from the example?

From my understanding, you want to rely on libp2p, so the best way is to look into `js-libp2p` examples, as the usage of libp2p transports/discovery modules are abstracted via a libp2p configuration.

As a side note, for general questions I recommend that you use [discuss.libp2p.io](https://discuss.libp2p.io) as you can get help from the libp2p community and also create content that might help others

**Comment by ubernaut** [comment]
This is exactly what I was looking for thanks a million @vasco-santos ! I now have the example up and running in my browser.  I'll direct similar questions toward the discussion group you linked.
