### ISSUE TITLE
Start SSL secured star server in LAN

### ISSUE THREAD

**Issue by khayliang** [libp2p/js-libp2p-webrtc-star#333]
Hi, I'm trying to setup a star server in LAN and I need to serve wss. I can't seem to get the DEPLOYMENT.md guide going on my PC. Any suggestions on how to get it started?

**Comment by lidel** [comment]
@khayliang you need a public IP for letsencrypt cert issuance to work.

For local development you may try self-signed certs, but then you need to import your custom CA to every browser that you use for testing. 

For further help try asking at https://discuss.ipfs.io/c/help/ – more eyeballs there :)
