### ISSUE TITLE
Secure connection in signaling server

### ISSUE THREAD

**Issue by VictorBjelkholm** [libp2p/js-libp2p-webrtc-star#36]
Connecting to the signaling server from an https page will emit a error in chrome currently, since the server is not secure. See error:

![](https://ipfs.io/ipfs/QmPSFKD6wbf9UZza44hRrSiwqzNFDsPBoQeVGdRwcUhmua)

**Comment by diasdavid** [comment]
yeah, we might just ship the sig server with a dumb cert just to make browsers happy.

I do want to have this quarter a sig server that is always on for everyone

**Comment by diasdavid** [comment]
For ref: https://github.com/ipfs/js-ipfs/issues/614

**Comment by VictorBjelkholm** [comment]
This has been shipped already! :tada:

**Comment by AquiGorka** [comment]
Sorry about the double posting, I think this belongs here: how can I execute my `star-signal` server locally with support for `wss`?

**Comment by AquiGorka** [comment]
Hmmmm, ok, ok. Thanks for the reply!
