### ISSUE TITLE
Tests fail to finish without aegir exit

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/js-libp2p-webrtc-star#364]
> There are further tests that fail to finish, I think node-wrtc is failing to close connections properly so I added --exit to the test run to simulate the previous behaviour of aegir but this really needs fixing.

@achingbrain in https://github.com/libp2p/js-libp2p-webrtc-star/pull/362

**Comment by lidel** [comment]
- waiting for fix in node-wrtc 
- we may speed it up by creating repro case (@achingbrain has more context)

**Comment by achingbrain** [comment]
This is sort of fixed now, by [adding these lines](https://github.com/libp2p/js-libp2p-webrtc-star/blob/master/packages/webrtc-star-transport/test/node.ts#L18-L20)

More context: https://github.com/node-webrtc/node-webrtc/issues/636#issuecomment-774171409
