### ISSUE TITLE
Error: Transport (WebRTCStar) could not listen on any available address

### ISSUE THREAD

**Issue by ratik21** [libp2p/js-libp2p-webrtc-star#403]
Following up after [this](https://github.com/libp2p/js-libp2p-webrtc-star/issues/402) issue, i tried to follow this comment to setup a local signalling server :: [https://github.com/libp2p/js-libp2p-webrtc-star/issues/238#issue-651546634](https://github.com/libp2p/js-libp2p-webrtc-star/issues/238#issue-651546634). So using `nginx + certbox` to generate certs, and then using docker-compose file, i was able to deploy the server locally.

Terminal log:
![image](https://user-images.githubusercontent.com/33264364/153524564-05ec95e0-be4a-4a41-854b-a10eb0778806.png)

Browser:
![image](https://user-images.githubusercontent.com/33264364/153524588-c4f3927c-8ae4-4fd2-b58e-854798d3780a.png)

So now i wanted to use it in an example (say peer discovery using `webrtc-star` transport). But i get the following error:
```bash
Error: Transport (WebRTCStar) could not listen on any available address
    at TransportManager.listen (/home/ratik/Zero/zChain/packages/zchain-core/node_modules/libp2p/src/transport-manager.js:201:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
![image](https://user-images.githubusercontent.com/33264364/153524703-692ac0ee-b6c8-4037-bda7-0dcc9efbffce.png)
 
NOTE: Using the public webrtc-star server works -- `wrtc-star1.par.dwebops.pub`, `wrtc-star2.sjc.dwebops.pub`.  
    
cc: @jjperezaguinaga

**Comment by ratik21** [comment]
Interestingly :: when i deploy using the heroku setup mentioned [here](https://suda.pl/free-webrtc-star-heroku/), the server get's deployed, and the peer discovery works  as well. But the local server mentioned above doesn't work. Trying to understand what's happening here :/

**Comment by mateuszjarzewski** [comment]
> Interestingly :: when i deploy using the heroku setup mentioned [here](https://suda.pl/free-webrtc-star-heroku/), the server get's deployed, and the peer discovery works as well. But the local server mentioned above doesn't work. Trying to understand what's happening here :/

I does not, it crashes when handling very first request.

**Comment by achingbrain** [comment]
@mateuszjarzewski there was a bug that caused a crash with the first request - it was [fixed a week ago](https://github.com/libp2p/js-libp2p-webrtc-star/pull/429), could you please try again with the latest version?

**Comment by BigLep** [comment]
@mateuszjarzewski : we're going to resolve since we believe we have fixed the issue per the comment above.  Feel free to reopen if that's not the case.
