### ISSUE TITLE
I wish it works.

### ISSUE THREAD

**Issue by mateuszjarzewski** [libp2p/js-libp2p-webrtc-star#417]
Is there an alternative to this server? Or maybe someone have like working binary of this server?

**Comment by mrlp4** [comment]
It seems like v0.1.4 of signaling server is actually working, but it keeps spamming log with `ReferenceError: __dirname is not defined` messages, which is a bit weird ofc.
But i have my app successfully connecting with star-signaling server while it showing 500 error instead of index.js

**Comment by mpetrunic** [comment]
@mrlp4 Could you post stacktrace?
