### ISSUE TITLE
Missing file index.html

### ISSUE THREAD

**Issue by RonanLabs** [libp2p/js-libp2p-webrtc-star#468]
Hello all, I found that there are missing file (index.html) when running the sample code.

**Environment setting:**
npm 8.11.0
node 16.16.0
@libp2p/webrtc-star-signalling-server ^2.0.2

**Error:**
![螢幕擷取畫面 (153)](https://user-images.githubusercontent.com/109357984/188351713-e750c662-4d65-4c3f-a70f-17a07171ea42.png)

**Sample code:**
![螢幕擷取畫面 (155)](https://user-images.githubusercontent.com/109357984/188351888-fa2c0afb-160b-45f3-9ce9-82b1b10d2c64.png)

**More information:**
![螢幕擷取畫面 (157)](https://user-images.githubusercontent.com/109357984/188352317-6c3eaf11-8fc8-4c20-b682-b20d85ff01fb.png)

![螢幕擷取畫面 (159)](https://user-images.githubusercontent.com/109357984/188352519-83f4671f-5b05-4962-94f5-befdfdf353e4.png)

Did I missing some configration when I import the libs?

**Comment by mpetrunic** [comment]
@RonanLabs Hey there, could you explain to us what are you trying to achieve?
