### ISSUE TITLE
Lack of good Linux and Windows support when used with Node.js

### ISSUE THREAD

**Issue by VictorBjelkholm** [libp2p/js-libp2p-webrtc-star#57]
There is a known issue on Ubuntu machine with node-webrtc, issue here: https://github.com/js-platform/node-webrtc/issues/281

Solution currently seems to be building node-webrtc from source, which takes long time and also lots of space. Currently trying out if it helps, will report back.

**Comment by VictorBjelkholm** [comment]
So, spent around one hour building node-webrtc from source (and about 18gbs...) and ended up getting a segfault instead of the x11 display issue.

**Comment by diasdavid** [comment]
@VictorBjelkholm could you convert this to documentation, please?

**Comment by diasdavid** [comment]
ping @VictorBjelkholm

**Comment by VictorBjelkholm** [comment]
Tried this again with the following versions:

```
{ 'libp2p-webrtc-star': '0.13.2',
  npm: '5.3.0',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.0',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.84',
  zlib: '1.2.8' }
```

On `Ubuntu 16.10` and everything now works fine. Seems like since version `0.0.62` of wrtc, they publish binaries for Ubuntu that works fine!

**Comment by diasdavid** [comment]
no seg faults?

**Comment by VictorBjelkholm** [comment]
@diasdavid nope, nada. Seems to be working fine now.
