### ISSUE TITLE
Not all tests are run in the firefox browser launched in TRAVIS

### ISSUE THREAD

**Issue by michaelfakhri** [libp2p/js-libp2p-webrtc-star#79]
Hey all

If you look at one of the more recent travis runs:
For e.g: https://travis-ci.org/libp2p/js-libp2p-webrtc-star/jobs/192418819 <-  This is one of the latest builds and it does not run the dial, discovery tests but it shows a pass even though karma timed out. 

Cheers

**Comment by diasdavid** [comment]
They are running, it just prints an awful amount of logs, see:

- https://travis-ci.org/libp2p/js-libp2p-webrtc-star/jobs/192418819#L2208
- https://travis-ci.org/libp2p/js-libp2p-webrtc-star/jobs/192418819#L2221
- https://travis-ci.org/libp2p/js-libp2p-webrtc-star/jobs/192418819#L2224

**Comment by michaelfakhri** [comment]
Yes it does!, those alsa print outs are just too annoying. I tried removing them once but without any success.

I still think the print outs you pointed are the mocha printouts when coverage is run not the actual karma ones as it can be seen from https://travis-ci.org/libp2p/js-libp2p-webrtc-star/jobs/192418819#L2125 for example
![screenshot from 2017-01-17 07-35-51](https://cloud.githubusercontent.com/assets/22283847/22020757/f5e5f82a-dc87-11e6-8230-3054791eede4.png)

**Comment by diasdavid** [comment]
ah, right, well the case seems to be that Firefox is not showing webrtc support, made https://github.com/libp2p/js-libp2p-webrtc-star/pull/80 to make it more clear. 

Now, firefox should have support, especially version 50, might be a issue with https://www.npmjs.com/package/webrtcsupport

**Comment by diasdavid** [comment]
nevertheless, browser tests are run in CircleCI correctly

**Comment by michaelfakhri** [comment]
Closing this, since the issue seems to have been fixed
