### ISSUE TITLE
Connect 2 peers through the signaling star

### ISSUE THREAD

**Issue by gavinmcdermott** [libp2p/js-libp2p-webrtc-star#85]
We're trying to connect 2 peers using `webrtc-star` and a signaling server in between. The diagram below is the setup.

![evernote snapshot 20170120 160906](https://cloud.githubusercontent.com/assets/302978/22169753/92594edc-df2b-11e6-9b31-2ae5946fdcc1.png)

After spending some time ~~failing~~ without success this afternoon, we figured it was likely something simple that is being missed. Based on our (growing :) ) understanding the following code should allow peerA to dial and connect to peerB...any pointers here?

```js
nodeFactory.create()
  .then((instance) => {
    node = instance
    return node.start()
  })
  .then(() => {
    // this is peerA
    const id = node.identity.id
    // our signaling server was @ 10.2.2.162:10000
    node._ipfs._peerInfo.multiaddr.add(`/libp2p-webrtc-star/ip4/10.2.2.162/tcp/10000/ws/ipfs/${id}`)

    let addP = promisify(node._ipfs._libp2pNode.swarm.transport.add)
    return addP('wstar', new WebRTCStar())
  })
  .then(() => {
    // we want to connect to peerB
    const peerInfo = new PeerInfo(PeerId.createFromB58String('QmQy9MiS5weQfpYP48cnBPoRgLbfK2zmpCQAU7tNb9VbAJ'))

    const dialP = promisify(node._ipfs._libp2pNode.swarm.dial)
    return dialP(peerInfo)
  })
```

**Comment by diasdavid** [comment]
@gavinmcdermott you have to pass the full multiaddr to a `swarm.dial`, you are just passing the PeerId currently

(Nice drawing btw 👌🏾🌟)

**Comment by ReidWilliams** [comment]
Thanks @diasdavid that helped! The other thing that we weren't getting right was we were adding the WebRTCStar transport to the swarm using ```swarm.transport.add``` but not calling ```swarm.listen``` before dialing. 

In case its helpful to others, here's the complete code that worked for us (left out the definition of a couople of functions for brevity)

```
let node
nodeFactory.create()
  .then((instance) => {
    node = instance
    return node.startWithOffset() // part of our node factory, just calls ipfs.start()
  })
  .then(() => {
    // add multiaddress with signaling server to our peer id
   // multiAddrString just builds a string like /libp2p-webrtc-star/ip4/10.2.2.162/tcp/10000/ws/ipfs/abc123`
    const ownAddress = multiaddr(multiAddrString(signalAddress, signalPort, node.identity.id))
    node._ipfs._libp2pNode.peerInfo.multiaddrs.push(ownAddress)

     // add web rtc star transport
    const rtc = new WebRTCStar()
    let addP = promisify(node._ipfs._libp2pNode.swarm.transport.add)
    return addP('wstar', rtc)
  })
  .then(() => {
    // must call listen after adding a new transport
    return promisify(node._ipfs._libp2pNode.swarm.listen())
  })
  .then(() => {
    // build peer info for the peer we want to dial
    const id = PeerId.createFromB58String(otherPeerIdHash)
    const otherPeer = new PeerInfo(id)
    const otherMultiAddressString = multiAddrString(signalAddress, signalPort, otherPeerIdHash)
    const otherAddress = multiaddr(otherMultiAddressString)
    otherPeer.multiaddr.add(otherAddress)

    return node._ipfs._libp2pNode.swarm.dial(otherPeer)
  })
```

**Comment by michaelfakhri** [comment]
Hey there, 

You guys did an excellent job figuring out and documenting all the little stuff that must happen for a connection.

But libp2pNode module handles a lot of these things if you do things slightly differently. So here is what you need to do to simplify the process a lot more:

- Create the node as you do above
-  do node._ipfs._libp2pNode.peerInfo.multiaddr.add(multiaddrs) as you do above (its equivalent to what you did above)
- only after adding your own address, you should start the node (this is important since, during the start function, the WebRTC star is created and a listener is also instantiated and started then)
- then you can use the _libp2pNode API to dial, for example you could do ....._lip2pNode.dialByMultiaddr(multiaddrs) (part of the api is available here https://github.com/ipfs/js-libp2p-ipfs-browser#api)

So to simplify the code:
```
let node

// do similar thing on both sides
nodeFactory.create()
  .then((instance) => {
    node = instance
    node._ipfs._libp2pNode.peerInfo.multiaddr.add(ownAddrs)
    return node.startWithOffset() // part of our node factory, just calls ipfs.start()
  })

// do this on one side
.then(() => {
  node._ipfs._libp2pNode.dialByMultiaddr(otherPeersMultiaddrs)
})
```

Hope this helped!

**Comment by diasdavid** [comment]
It seems you are calling a lot of the internals, which might be causing some havoc.

> nodeFactory.create()
  .then((instance) => {
    node = instance
    return node.startWithOffset() // part of our node factory, just calls ipfs.start()
  })

If you start the daemon here, you can't later start adding more multiaddrs and call listen again, it is not built to support that.

Check this example - https://github.com/ipfs/js-ipfs/tree/docs/interop-examples/examples/transfer-files/complete to see how to add webrtc-star multiaddrs and how to spawn the node.

**Comment by ReidWilliams** [comment]
@michaelfakhri and @diasdavid thanks guys, we'll change it so we don't use so many internals.

**Comment by gavinmcdermott** [comment]
Thanks everyone! @michaelfakhri, I have a question regarding the above snippet: If I want to add a transport 'manually', it looks like I need access to the node's `_libp2pNode` instance; which is set upon the [call to `goOnline`](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/libp2p.js#L21). But from my understanding, after `goOnline` is called we can no longer add transports.

Any direction on where my understanding is off or how I can manually add a specific transport to an ipfs instance?

**Comment by diasdavid** [comment]
I believe this question is now answered. Closing this one then.
