### ISSUE TITLE
Get star-signal.cloud.ipfs.team a nice Certificate.

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-webrtc-star#87]
Following: https://github.com/libp2p/js-libp2p-webrtc-star/pull/84#discussion_r97209818

**Comment by lgierth** [comment]
Here: https://star-signal.cloud.ipfs.team/

That was surprisingly painless thanks to https://github.com/dokku/dokku-letsencrypt

**Comment by diasdavid** [comment]
\o/ Tests pass with https! No more need for 'Load unsafe scripts' 

//cc @haadcode
